<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Cards\menuCard.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Cards\newEventCard.json">
    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.0" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs" Version="4.23.0" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Roboto.Sdk/Roboto.Sdk.csproj" />
    <ProjectReference Include="../Roboto.Dtos/Roboto.Dtos.csproj" />
  </ItemGroup>

    <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
